<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\FortniteSkinWiki;
use Carbon\Carbon;

class FortniteSkinWikiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        FortniteSkinWiki::insert([
            ['name'=>'A.I.M.', 'vbuck_price' => "2000", 'rarity' => 'Legendary' ,'season' => "6" , 'image' => 'BlackKnight.jpg'],
            ['name'=>"Arachne", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "6" , "image" => ''],
            ['name'=>"Ark", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "7" , "image" => ''],
            ['name'=>"Backlash", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"BattleHound", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "3" , "image" => ''],
            ['name'=>"BlackKnight", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "8" , 'image' => 'BlackKnight.jpg'],
            ['name'=>"Blackheart", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"Blastoff", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"Calamity", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "6" , "image" => ''],
            ['name'=>"Carbide", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "4" , "image" => ''],
            ['name'=>"ChompSr.", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5", "image" => ''],
            ['name'=>"Crackshot", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "1" ,'image' => 'CrackShot.jpg'],
            ['name'=>"Criterion", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "4" , "image" => ''],
            ['name'=>"CuddleTeamLeader", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "2" ,'image' => 'CuddleTeamLeader.jpg'],
            ['name'=>"Cyclo", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "2" , "image" => ''],
            ['name'=>"DarkVanguard", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "3" , "image" => ''],
            ['name'=>"DarkVertex", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "9" , "image" => ''],
            ['name'=>"DarkVoyager", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "3" , "image" => ''],
            ['name'=>"Deadeye", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "1" , "image" => ''],
            ['name'=>"Deadfire", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "6" , "image" => ''],
            ['name'=>"Dire", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "6" , "image" => ''],
            ['name'=>"DJBop", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "7" , "image" => ''],
            ['name'=>"Drift", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5" , "image" => ''],
            ['name'=>"DynamoDancer", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"Enforcer", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5" , "image" => ''],
            ['name'=>"Eon", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "6" , "image" => ''],
            ['name'=>"EternalKnight", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "3" , "image" => ''],
            ['name'=>"Fade", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "3" , "image" => ''],
            ['name'=>"Fate", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "4" , "image" => ''],
            ['name'=>"Firebrand", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"Flytrap", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "4" , "image" => ''],
            ['name'=>"Frostbite", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5" , "image" => ''],
            ['name'=>"Fusion", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "1" , "image" => ''],
            ['name'=>"Galaxia", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"GalaxyScout", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "2" , "image" => ''],
            ['name'=>"GearSpecialistMaya", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "2" , "image" => ''],
            ['name'=>"Glimmer", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "7" , "image" => ''],
            ['name'=>"Glow", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "10" , "image" => ''],
            ['name'=>"Havoc", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "3" , "image" => ''],
            ['name'=>"Hime", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5" , "image" => ''],
            ['name'=>"Hunter", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"Hybrid", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "8" , "image" => ''],
            ['name'=>"Hypersonic", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"Inferno", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "8" , "image" => ''],
            ['name'=>"JohnWick", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "9" , "image" => ''],
            ['name'=>"Joltara", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"Krampus", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "7" , "image" => ''],
            ['name'=>"Leviathan", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "3" , "image" => ''],
            ['name'=>"LoveRanger", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "2" ,'image' => 'LoveRanger.jpg'],
            ['name'=>"Luxe", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "8" , "image" => ''],
            ['name'=>"Lynx", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "7" , "image" => ''],
            ['name'=>"Magnus", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5" , "image" => ''],
            ['name'=>"Malice", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "8" , "image" => ''],
            ['name'=>"Menace", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5" , "image" => ''],
            ['name'=>"Midas", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "2" , "image" => ''],
            ['name'=>"MidasRex", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"MoistyMerman", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "4" , "image" => ''],
            ['name'=>"Musha", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5" , "image" => ''],
            ['name'=>"Oblivion", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "4" , "image" => ''],
            ['name'=>"Omega", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"Omen", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "4" , "image" => ''],
            ['name'=>"Oppressor", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "10" , "image" => ''],
            ['name'=>"Oro", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "2" , "image" => ''],
            ['name'=>"P.A.N.D.ATeamLeader", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5" , "image" => ''],
            ['name'=>"Polarity", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"PowerChord", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "3" , "image" => ''],
            ['name'=>"Predator", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5" , "image" => ''],
            ['name'=>"Ragnarok", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5" , "image" => ''],
            ['name'=>"Raptor", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "1" ,'image' => 'Raptor.jpg'],
            ['name'=>"Ravage", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "1" , "image" => ''],
            ['name'=>"Raven", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5" , "image" => ''],
            ['name'=>"RedKnight", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "1",'image' => 'RedKnight.jpg'],
            ['name'=>"Rex", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "3" , "image" => ''],
            ['name'=>"RogueSpiderKnight", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "10" , "image" => ''],
            ['name'=>"RoseTeamLeader", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "3" , "image" => ''],
            ['name'=>"Rox", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "9" , "image" => ''],
            ['name'=>"Ruin", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "8" , "image" => ''],
            ['name'=>"Sentinel", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "9" , "image" => ''],
            ['name'=>"Shogun", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "6" , "image" => ''],
            ['name'=>"Singularity", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "9" , "image" => ''],
            ['name'=>"SkyStalker", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "4" , "image" => ''],
            ['name'=>"Sorana", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "1" , "image" => ''],
            ['name'=>"SpiderKnight", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "6" , "image" => ''],
            ['name'=>"SpireAssassin", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "6" , "image" => ''],
            ['name'=>"Supersonic", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "8" , "image" => ''],
            ['name'=>"Tempest", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "9" , "image" => ''],
            ['name'=>"TheIceKing", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "7" , "image" => ''],
            ['name'=>"TheIceQueen", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "7" , "image" => ''],
            ['name'=>"TheMightyVolt", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"ThePrisoner", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "7" , "image" => ''],
            ['name'=>"TheReaper", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "3" , "image" => ''],
            ['name'=>"TheScientist", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "10" , "image" => ''],
            ['name'=>"TheVisitor", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"TriceraOps", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "3" , "image" => ''],
            ['name'=>"Valkyrie", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5"  , "image" => ''],
            ['name'=>"Valor", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"Velocity", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "9" , "image" => ''],
            ['name'=>"Vendetta", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "9" , "image" => ''],
            ['name'=>"Vertex", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "4" , "image" => ''],
            ['name'=>"Vi", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5" , "image" => ''],
            ['name'=>"Wanderlust", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "4" , "image" => ''],
            ['name'=>"Warpaint", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "3" , "image" => ''],
            ['name'=>"WildCard", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "5" , "image" => ''],
            ['name'=>"Wukong", 'vbuck_price' => "2000", 'rarity' => "Legendary" ,'season' => "2",'image' => 'Wukong.jpg'],
            ['name'=>"Zenith", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "7" , "image" => ''],
            ['name'=>"Zero", 'vbuck_price' => "2000", 'rarity' => "Legendary",'season' => "1" , "image" => '']
        ]);
    }
}
